// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from '/Users/jiangxin/test_project/docs-docusaurus/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"easycomponent","description":"测试文档","version":"0.0.1","license":"MIT","authors":[]},
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      themeConfig: {"footer":false,"prefersColor":{"default":"light","switch":true},"name":"猿极客","deviceWidth":375,"nav":[{"title":"组件","link":"/components/agreement"},{"title":"hook","link":"/hook"}],"logo":"https://dumi-theme-chakra.deno.dev/dumi-theme-chakra-logo.png"},
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
