// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/jiangxin/test_project/docs-docusaurus/node_modules/dumi-theme-mobile/dist/slots/Device/index.js';
