// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/paginationscrollview":{"path":"components/paginationscrollview","id":"docs/components/paginationscrollview","parentId":"DocLayout"},"docs/components/agreementpdf":{"path":"components/agreementpdf","id":"docs/components/agreementpdf","parentId":"DocLayout"},"docs/components/agreement":{"path":"components/agreement","id":"docs/components/agreement","parentId":"DocLayout"},"docs/hook/useUpdateEffect":{"path":"hook/use-update-effect","id":"docs/hook/useUpdateEffect","parentId":"DocLayout"},"docs/components/share":{"path":"components/share","id":"docs/components/share","parentId":"DocLayout"},"docs/hook/useMemoize":{"path":"hook/use-memoize","id":"docs/hook/useMemoize","parentId":"DocLayout"},"docs/components/pay":{"path":"components/pay","id":"docs/components/pay","parentId":"DocLayout"},"docs/hook/useLockFn":{"path":"hook/use-lock-fn","id":"docs/hook/useLockFn","parentId":"DocLayout"},"docs/hook/index":{"path":"hook","id":"docs/hook/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout","prerender":false}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/jiangxin/test_project/docs-docusaurus/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/.dumi/tmp-production/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/jiangxin/test_project/docs-docusaurus/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-mobile__dist__layouts__DemoLayout" */'/Users/jiangxin/test_project/docs-docusaurus/node_modules/dumi-theme-mobile/dist/layouts/DemoLayout.js')),
'docs/components/paginationscrollview': React.lazy(() => import(/* webpackChunkName: "docs__components__paginationscrollview.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/components/paginationscrollview.md')),
'docs/components/agreementpdf': React.lazy(() => import(/* webpackChunkName: "docs__components__agreementpdf.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/components/agreementpdf.md')),
'docs/components/agreement': React.lazy(() => import(/* webpackChunkName: "docs__components__agreement.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/components/agreement.md')),
'docs/hook/useUpdateEffect': React.lazy(() => import(/* webpackChunkName: "docs__hook__useUpdateEffect.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/hook/useUpdateEffect.md')),
'docs/components/share': React.lazy(() => import(/* webpackChunkName: "docs__components__share.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/components/share.md')),
'docs/hook/useMemoize': React.lazy(() => import(/* webpackChunkName: "docs__hook__useMemoize.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/hook/useMemoize.md')),
'docs/components/pay': React.lazy(() => import(/* webpackChunkName: "docs__components__pay.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/components/pay.md')),
'docs/hook/useLockFn': React.lazy(() => import(/* webpackChunkName: "docs__hook__useLockFn.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/hook/useLockFn.md')),
'docs/hook/index': React.lazy(() => import(/* webpackChunkName: "docs__hook__index.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/hook/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/jiangxin/test_project/docs-docusaurus/packages/componentdoc/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/jiangxin/test_project/docs-docusaurus/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
