name: 重复使用的工作流

on:
  workflow_call:
    inputs:
      docname:
        required: true
        type: string   
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      REMOTE_USER:
        required: true
      REMOTE_HOST:
        required: true    
jobs:
  install-npm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_actions
        uses: actions/checkout@v3
      - name: 初始化node环境
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          npm -v
          npm install
      - name: 打包 ${{ inputs.docname }} 文档
        if: inputs.docname=='webdoc'
        run: npm run build-webdoc
      - name: 上传${{inputs.docname}}文档
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.docname }}
          path: ${{github.workspace}}/packages/${{ inputs.docname }}/build/
          retention-days: 1
  publish-server:
    runs-on: ubuntu-latest
    needs: install-npm
    steps:
      - name: 下载${{inputs.docname}}文档
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.docname }}
          path: ${{github.workspace}}/${{ inputs.docname }}
      - name: 布署到腾讯去服务器
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          SOURCE: ./${{ inputs.docname }}/
          TARGET: "/www/doc/${{ inputs.docname }}"
