name: 自动打包文档
run-name: ${{ github.actor }} 文档自动打开发布工作流
on:
  push:
    paths:
      - ".github/workflows/*.yml"
      - "packages/**/*.{md,mdx,tsx,js}"
      - "packages/**/styles.modules.css"
jobs:
  install-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_actions
        uses: actions/checkout@v3
      - name: 初始化node环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g pnpm
      - run: |
          pnpm -v
          pnpm install
      - name: cache node_modules
        uses: actions/cache@v3
        with: 
          path: |
            "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}  
      - name: 打包文档
        run: pnpm build-webdoc
      - name: 上传文档
        uses: actions/upload-artifact@v3
        with:
          name: mywebdoc
          path: ${{github.workspace}}/packages/webdoc/build/
