name: 自动打包文档
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  install-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_actions
        uses: actions/checkout@v3
      - name: 初始化node环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: npm install -g pnpm
      - run: |
          pnpm -v
          pnpm install
      - name: 打包文档
        run: pnpm build-webdoc
